language: r
sudo: required
cache: packages

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

