language: r
sudo: required
cache: packages

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

before_install:
  - git clone https://github.com/endpoints/endpoints-example.git
  - cd endpoints-example
  - npm install
  - PORT=8088 npm start

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

